### PR TITLE
read path for global config from picasso config file

### PR DESCRIPTION
**Pull request by HolgerPollyNet**
There was still a bug in reading the global config file specified in the picasso config file--> this did not work, instead the default was always used.

### CODE REVIEW

**Comment by HolgerPollyNet** [comment]
@ulysses78 Please have  a quick look if my bug fixes interfere with something of your devs. Thanks!

**Review by ulysses78 — CHANGES_REQUESTED** [review]
## picassoProcV3.m
you implemented the global config file now the "hard way". this one can be set as an optional parameter when calling the picassoProcV3-function.
(see line 73 & 83). But I think that is ok, because this config file is always part of the repo.

## requirements.txt
Does picasso 4.0 work on your windows machine now with this requs?

Please let the following packages in the requs:
- docutils
- pycodestyle
- requests
- all sphinx packages
- urllib3

I didn't needed the doc and sphinx packages so far for picasso 4.0, but it will be neccessary, when updating the documenations

**Comment by HolgerPollyNet** [comment]
I don't think it is in a hard way. because the function just a line above just overwrites the default values. So if the path is not set, it stays as default....

**Review by ulysses78 — APPROVED** [review]
looks good

**Pull request merged**
