### PR TITLE
Do not merge files of whole day if difference found

### PR DESCRIPTION
**Pull request by ulysses78**

### CODE REVIEW

**Comment by HolgerPollyNet** [comment]
what means skipped in this sense? Will then the files processed anyhow? but as single files as prior the 24h era?

**Comment by HolgerPollyNet** [comment]
Okay, but I fear that your data stream monitor is then one major source for finding unprocessed days......

**Review by HolgerPollyNet — APPROVED** [review]
looks good, even though I did not test it!

**Comment by ulysses78** [comment]
> Okay, but I fear that your data stream monitor is then one major source for finding unprocessed days......

That is exactly what the data-stream-monitor was build for ;-)

**Pull request merged**
