### PR TITLE
changes related to issue #196 ... implement 1-step Poliphon

### PR DESCRIPTION
**Pull request by AthenaAugousta**
Poliphon step-1 is now implemented. Please review!

### CODE REVIEW

**Comment by HolgerPollyNet** [comment]
@AthenaAugousta @ulysses78 Thanks for uploading it looks indeed very promising. However, could you please try to resolve the conflicts first on your own and then upload a new (maybe locally merged version) for a pull request?

Thanks!

**Comment by HolgerPollyNet** [comment]
In my opinion it would be easiest, if you pull the latest dev. Copy the modification you had to made in PicassoV3 in the pulled version: 
grafik

and
grafik

And the add the new files 
grafik

and modify the global config as done
grafik
 and test and no conflict should be there anymore.

**Comment by ulysses78** [comment]
@AthenaAugousta ... do you know how to pull the newest dev-branch?

**Comment by AthenaAugousta** [comment]
> @AthenaAugousta ... do you know how to pull the newest dev-branch?

_git pull dev Athena_, right?

**Comment by AthenaAugousta** [comment]
Thank you @ulysses78! Now that I have done the modifications to the dev branch (locally) I should commit the changes and then `git push origin dev`?

**Comment by ulysses78** [comment]
I think it is best not to do the changes on the dev branch, but create a new branch, where you make your changes and afterwards push this new branch to github.

**Comment by ulysses78** [comment]
pushing the new branch:
```git push origin new-branch-name```

**Pull request closed without merging**
