### PR TITLE
corrected lambda entry of POLIPHON in donefilelist to 532nm

### PR DESCRIPTION
**Pull request by ulysses78**
The wavelength for the POLIPHON plots in the donefilelist has been changed in ``lib/io/pollyWriteDonelist.m`` from 355 nm to 532 nm.

### CODE REVIEW

**Review by HolgerPollyNet — APPROVED** [review]

**Comment by ulysses78** [comment]
You mean like in the pollyconfig file for x,y,z ranges?:
```
"xLim_Profi_Bsc": [-0.05, 3]
"zLim_att_beta_532": [0, 5]
```
If so, I can use the zLim_att_beta_532 value for the x-range. OK?

**Comment by ulysses78** [comment]
I added this option here: https://github.com/PollyNET/Pollynet_Processing_Chain/pull/234

**Comment by HolgerPollyNet** [comment]
well z-lim is not correct, it would be xLim, and it is also not att beta. Thus the correct name would be :
xLim_beta_532_Poliphon

**Comment by ulysses78** [comment]
I thought the zlim range for 3dim plots should be the same as for the related profile plots. But nevertheless... attbsc vs. bsc - my fault, sorry. Isn't there any bsc range config parameter for 532nm so far?

**Comment by HolgerPollyNet** [comment]
yes there is ;-), but It would still be better to have an own one :-)

**Comment by HolgerPollyNet** [comment]
Great! Correct. Could you do the same for the yLim_beta_532_Poliphon?

**Comment by ulysses78** [comment]
> Great! Correct. Could you do the same for the yLim_beta_532_Poliphon?

Of Course. With a range for yLim_beta_532_Poliphon of [0, 8] km?

**Comment by ulysses78** [comment]
I also had to correct the x+y-lim entries for POLIPHON in the file lib/visualization/pollyDisplayProfiles.m . see here: https://github.com/PollyNET/Pollynet_Processing_Chain/pull/234/commits/aae166b60f4fa3f6b20095f98755f0cc874ffa20

**Pull request merged**
