### PR TITLE
Poliphon plots

### PR DESCRIPTION
**Pull request by ulysses78**
added POLIPHON profile-plotting

### CODE REVIEW

**Comment by HolgerPollyNet** [comment]
Is the POLIPHON currently produced from Raman only or from Klett as well?

Anyhow the nomenclature should be improved for clarity:
image=../2023_10_02_Mon_LACROS_06_00_01_0651_0750_POLIPHON.png --> image=../2023_10_02_Mon_LACROS_06_00_01_0651_0750_POLIPHON_1step_Raman.png

and 
product_type=POLIPHON --> product_type=POLIPHON_step1_Raman

If Klett is available, of course the same.... 

Can you do this please? @AthenaAugousta @ulysses78

**Comment by ulysses78** [comment]
I have renamed the "POLIPHON" plots to "POLIPHON_step1_Raman", same to the product-type in the donefilelist. The Klett results are not implemented so far.

**Comment by HolgerPollyNet** [comment]
Great, I will test this afternoon. Is your branch on rsd2 up to date?

**Comment by ulysses78** [comment]
> Great, I will test this afternoon. Is your branch on rsd2 up to date?

Yes the branch ''poliphon_plots" on rsd2 in the experimental-akl folder is up to date.

**Comment by AthenaAugousta** [comment]
What is the status on the plotting? Did the testing take place?

**Comment by HolgerPollyNet** [comment]
@ulysses78  The wavelength in the done file list is not correct, even though not yet needed. But in future please insert a fill value instead of 355. 
@AthenaAugousta as we start working on Poliphon at 355 nm, we also should introduce the wavelength for the Poliphon products: 

_lidar=pollyxt_cpv
location=Mindelo
starttime=20210629 12:00:00
stoptime=20210629 12:45:30
last_update=20210629 12:00:01
**lambda=355**
image=recent_plots_new/pollyxt_cpv/2021/06/29/2021_06_29_Tue_CPV_12_00_01_1200_1227_POLIPHON_step1_Raman.png
level=0
info=Meteorological data from GDAS1 at mindelo on 20210629 12 UTC.
nc_zip_file=202106/2021_06_29_Tue_CPV_12_00_01.nc.zip
nc_zip_file_size=28041372
active=1
GDAS=1
GDAS_timestamp=20210629 12:00:00
lidar_ratio=50
software_version=3.6
product_type=POLIPHON_step1_Raman
product_starttime=20210629 12:00:00
product_stoptime=20210629 12:27:07_

**Comment by ulysses78** [comment]
The wavelength was adjusted in the donefilelist. See pull-request: https://github.com/PollyNET/Pollynet_Processing_Chain/pull/233

**Pull request merged**
