### PR TITLE
Andi branch 01

### PR DESCRIPTION
**Pull request by HolgerPollyNet**
changes to data base interface  to be compatible with Matlab 2018+. See Issue #120

### CODE REVIEW

**Review by ZPYin — CHANGES_REQUESTED** [review]
First of all, thanks for sending this PR and reporting the Matlab version issue for database connection.

But unfortunately, this commit cannot be executed successfully in Matlab 2014a under my test. Please confirm it.

The first objective of Pollynet Processing Chain is to support the NRT data processing in our data server. And only Matlab 2014a is installed in the server. So we have to make sure everything is OK at the old Matlab version.

An possible fix for this PR is to add Matlab version check and using different database connection approaches according to the version.

**Comment by HolgerPollyNet** [comment]
Hey @ulysses78, I think you need to impelment your chnages depending of the matlab version. Using the command "version" could be an option, and then doiung a simple if Matlab version before 2018 then as is else  new command.

**Comment by ulysses78** [comment]
Yes, I will start to implement a version control request.

**Review by ZPYin — CHANGES_REQUESTED** [review]
Thanks for your efforts in this PR.

Unfortunately, there are still version issues with this PR. 
`""` is for string type, but `string` type was introduced in Matlab R2016b. The same for Matlab function of `split`.

Below is a quick fix for your PR
```matlab
% replace" release = split(version, "("); with the command below.
release = strsplit(version, `(`);
```

**Comment by ulysses78** [comment]
I replaced the function split with strsplit. Hopefully it works now ;-)

**Review by ZPYin — APPROVED** [review]
Well done!!!
Thanks for your PR.

**Comment by ulysses78** [comment]
By the way... in this branch I also added the variable 'tilt_angle' for the following files:
```
lib/io/pollySaveAttnBeta.m
lib/io/pollySaveNRAttnBeta.m
lib/io/pollySaveOCAttnBeta.m
lib/io/pollySaveOverlap.m
lib/io/pollySaveVDR.m
lib/io/pollySaveWV.m
```

**Pull request merged**
