### PR TITLE
improvement(pollyxt_overlap): new overlap correction

### PR DESCRIPTION
**Pull request by ZPYin**
using the weighted mean to merge far-range and near-range signal (#49 )

### CODE REVIEW

**Comment by ZPYin** [comment]
wrong PRs brach

**Comment by HolgerPollyNet** [comment]
Hi Zhenping, as usual, incredible work. In my opinion both methods (overlapcorrmode 2 and 3) work well. method 2 has significantly improved, but 3 is good as well. I see slight differences. I think I have to make a sensitivity analysis what I consider to be better, but in principle it could be pushed to the server.

**Comment by ZPYin** [comment]
It was pushed to the server in the 'dev' branch. So far, it works. But if you have ideas regarding improve the overlap correction, just let me know.

I will read the EARLINET techinical paper again when I have time, to see whether I can implement the sophisticated algorithm.

**Comment by HolgerPollyNet** [comment]
in principle I do usually the same.
    For PollyXT for example, I calculate the signal ratio beteen FF and
    NF, then normalize it with its mean value between 1.5 and 2 km, and
    then use this as overlap function below 1.5 km. Thus I assume that
    between 1.5 and 2 km both signals have full overlap.
    
    Best
    Holger
    
    Am 01.05.2020 um 01:53 schrieb ZPYin:
    
    
      
      It was pushed to the server in the 'dev' branch. So far, it
        works. But if you have ideas regarding improve the overlap
        correction, just let me know.
      I will read the EARLINET techinical paper again when I have
        time, to see whether I can implement the sophisticated
        algorithm.
      —
        You are receiving this because your review was requested.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PollyNET/Pollynet_Processing_Chain/pull/50#issuecomment-622179940",
"url": "https://github.com/PollyNET/Pollynet_Processing_Chain/pull/50#issuecomment-622179940",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    -- 
 *****************************************************
 Dr. Holger Baars (Dipl.-Met.)
 Leibniz Institute for Tropospheric Research (TROPOS)
 Permoserstr. 15
 04318 Leipzig, Germany
 phone: ++49 341 2717 7314
 fax: ++49 341 2717 99 7314
 email: baars@tropos.de
 internet: http://www.tropos.de
 ****************************************************

**Pull request closed without merging**
